---
- name: Add SSH credentials to global credentials store
  uri:
    url: http://{{jenkins_hostname}}:{{jenkins_http_port}}{{jenkins_url_prefix}}/scriptText/
    method: POST
    body: "script={{lookup('template', 'templates/add-credentials-to-credentials-store.groovy.j2')|urlencode}}"
    HEADER_Content-Type: "application/x-www-form-urlencoded"
