--- # Setup Jenkins slave node environment
- name: Create Jenkins system user on slave node
  user: name={{jenkins_user}} home={{jenkins_home}} system=yes
        generate_ssh_key=yes
- name: Create Jenkins workspace directory on slave node
  file: name={{jenkins_workspace}}
        owner={{jenkins_user}}
        group={{jenkins_user}}
        state=directory
- name: Configure sudoers for Jenkins system user
  lineinfile: dest="/etc/sudoers.d/{{jenkins_user}}"
              line="{{jenkins_user}} ALL=(ALL) NOPASSWD:ALL"
              state=present
              create=yes
              mode=0440
              validate='visudo -cf %s'
- name: Install Python httplib2
  pip: name=httplib2 state=latest
- name: Download slave.jar from Jenkins server
  become_user: jenkins
  uri:
    url:  "https://{{hostvars['jenkins-master']['inventory_hostname']}}/jnlpJars/slave.jar"
    dest: "{{jenkins_home}}/slave.jar"
    user: "{{jenkins_slave_user_name}}"
    password: "{{jenkins_slave_user_password}}"
    validate_certs: no
    force_basic_auth: true
    status_code: 200, 304
- name: Install Jenkins slave systemd service
  template: src=templates/jenkins-slave.service.j2
            dest=/etc/systemd/system/jenkins-slave.service
            owner=root group=root mode=0644
- name: Start Jenkins slave service
  service: name=jenkins-slave enabled=true state=started
